CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    lastname VARCHAR(64) NOT NULL DEFAULT "",
    firstname VARCHAR(64) NOT NULL DEFAULT "",
    role VARCHAR(1) NOT NULL DEFAULT 'U'
);